secrets:
  credentials_vault_pass:
    file: ./config/credentials.vault.pass


services:
  server:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "13080:80" # Nginx
      - "13500:5000" # API
      - "13555:5555" # Flower
    networks:
      - mc-net
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    secrets:
      - credentials_vault_pass
    volumes:
      #- ${SSH_AUTH_SOCK}:/ssh-agent:ro
      - ${PWD}/.local/config:/app/config
      #- ${PWD}/.local/home:/home/app/
      - ${PWD}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /Users/phil/.local/share/containers/podman/machine/podman.sock:/var/run/podman.sock:ro
    environment:
      #- SSH_AUTH_SOCK=/ssh-agent
      #- SSH_CONFIG=/data/ssh_config
      - DEV_MODE=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MONGODB_URL=mongodb://admin:adminpassword@mongodb:27017?authSource=admin
      - HOST_DATA_DIR=${PWD}/data
      - HOST_CONFIG_DIR=${PWD}/config
      - CONFIG_DIR=/app/config
      - RESOURCES_DIR=/app/resources
      - DATA_DIR=/data
      #- VAULT_FILE=/app/config/credentials.vault
      - VAULT_PASS_FILE=/run/secrets/credentials_vault_pass
    env_file:
      - ./.env.docker.local
    depends_on:
      - redis
      - mongodb
    develop:
      watch:
        - action: sync+exec
          path: ./src
          target: /app/src
          ignore:
            - "__pycache__/"
            - "*.pyc"
            - "*.egg-info/"
            - "x*.py"
          exec:
            command: ["supervisorctl", "restart", "all"]
        - action: sync
          path: ./resources
          target: /app/resources
        - action: rebuild
          path: ./container
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: Containerfile
        - action: restart
          path: ./.env.docker.local

  redis:
    image: redis:latest
    ports:
      - "13379:6379"
    #expose:
    #  - "6379"
    networks:
      - mc-net
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "13017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_ROOT_AUTHENTICATION_DATABASE=admin
    networks:
      - mc-net
    volumes:
      - mongo-data:/data/db


volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local

networks:
  mc-net:
    driver: bridge
    name: mc-net
