

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13080:8000"
    networks:
      - kloudia-net
    volumes:
      - ./config:/app/config:ro
      - ./data:/data
    environment:
      - DATA_DIR=/data
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URL=mongodb://mongodb:27017
    links:
      - redis
      - mongodb
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    ports:
      - "13379:6379"
    networks:
      - kloudia-net
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "13017:27017"
    networks:
      - kloudia-net
    volumes:
      - mongo-data:/data/db


volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local

networks:
  kloudia-net:
    driver: bridge
