

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13080:8000"
      - "13555:5555"
    networks:
      - mc-net
    volumes:
      - ${PWD}/config:/app/config:ro
      - ${PWD}/data:/data
      - ${PWD}/resources:/app/resources:ro
      - ${HOME}/.ssh:/home/app/.ssh:ro
      #- ${SSH_AUTH_SOCK}:/ssh-agent:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /Users/phil/.local/share/containers/podman/machine/podman.sock:/var/run/podman.sock:ro
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    #  - "localmachine:host-gateway"
    environment:
      #- SSH_AUTH_SOCK=/ssh-agent
      - HOST_DATA_DIR=${PWD}/data
      - HOST_CONFIG_DIR=${PWD}/config
      - CONFIG_DIR=/app/config
      - RESOURCES_DIR=/app/resources
      - DATA_DIR=/data
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MONGODB_URL=mongodb://admin:adminpassword@mongodb:27017?authSource=admin
    env_file:
      - .env.docker.local
    depends_on:
      - redis
      - mongodb
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - "__pycache__/"
            - "*.pyc"
            - "*.egg-info/"
            - "x*.py"
        - action: rebuild
          path: ./docker
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile

  redis:
    image: redis:latest
    ports:
      - "13379:6379"
    #expose:
    #  - "6379"
    networks:
      - mc-net
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "13017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_ROOT_AUTHENTICATION_DATABASE=admin
    networks:
      - mc-net
    volumes:
      - mongo-data:/data/db


volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local

networks:
  mc-net:
    driver: bridge
    name: mc-net
