[metadata]
name = "mc"
version = "1.0.0"
description = "A sample web project deployment configuration"


[vars]
python_version = "3.11"
app_name = "mc"
app_entrypoint = "src/server.py"
app_port = "8080"
image_name = "mc:latest"
dockerhub_repo = "fmlabs/mc:latest"


[build]
[build.app]
what = "python-app"
#command_before = "cp -f ../rx/dist/rx*.whl ./libs/ && uv sync --upgrade"
command = "uv build"

[build.wheel]
what = "python-wheel"
command = "uv build --wheel"

[build.binary]
what = "python-binary"
command = "./build_bin.sh"

[build.image]
what = "image"
command="docker build -f Containerfile -t mc:latest ."


[publish]
[publish.image]
what = "image"
src="mc:latest"
dest="mc:${version}"

[publish.image-dockerhub]
what = "image"
src="mc:${version}"
dest="docker.io/fmlabs/mc:latest"
#dest="dockerhub://fmlabs/mc:latest"

[publish.container-local]
what = "container"
engine = "docker"
src="mc:latest"
dest="unix:///var/run/docker.sock"
command_before = "rx build image"

#[publish.compose-local]
#what = "compose"
#dest="docker://"
#compose_file = "docker-compose.local.yml"
#
#[publish.compose-local-podman]
#what = "compose"
#dest="podman://"
#
#[publish.compose-remote]
#what = "compose"
#dest="ssh://user@remotehost"
#
#[publish.compose-ec2]
#what = "compose"
#dest="ec2://user@ec2-instance"
#
#[publish.kubernetes]
#what = "kubernetes"
#dest="k8s://"


# RUN CONFIGS
[run]
[run.lint]
command = "uv lint"

[run.devserver]
command = "uvicorn --app-dir ./src server:app --reload"

[run.celery-worker-local]
command = "celery --workdir ./src -A celery_worker.celery worker --loglevel=INFO -E"

[run.celery-beat-local]
command = "celery --workdir ./src -A celery_worker.celery beat --loglevel=INFO"

[run.celery-flower-local]
command = "celery --workdir ./src -A celery_worker.celery flower --loglevel=INFO --port=5555"

[run.devstack-up]
command_before = "rx build app"
command = "docker-compose -f compose.dev.yaml up --build --force-recreate --watch"

[run.devstack-down]
command = "docker-compose -f compose.dev.yaml down"

[run.podstack-up]
command_before = "rx build app"
command = "podman compose -f compose.dev.yaml up --build --force-recreate --watch"

[run.podstack-down]
command = "podman compose -f compose.dev.yaml down"

# PIPELINES
[pipelines]
local-deploy = ["build app", "build image", "publish compose-local", "publish compose-local-podman"]
full-deploy = ["build app", "publish image", "publish compose-local", "publish kubernetes"]
