---

# Default site configuration
- name: Add default site configuration
  template:
    src: site.default.jinja2
    dest: /etc/nginx/sites-available/default
    force: yes
    owner: root
    group: root
    mode: 0644
  #notify: restart nginx

- name: Enable default site
  file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
  notify: reload nginx

