- name: Install required packages
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
    state: present
    update_cache: yes


- name: Add NGINX signing key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present


- name: Add NGINX repository
  apt_repository:
    repo: "deb https://nginx.org/packages/debian/ {{ ansible_lsb.codename | lower }} nginx"
    state: present
    filename: nginx


- name: Add NGINX source repository
  apt_repository:
    repo: "deb-src https://nginx.org/packages/debian/ {{ ansible_lsb.codename | lower }} nginx"
    state: present
    filename: nginx


- name: Update apt package list after adding NGINX repository
  apt:
    update_cache: yes
