---

- hosts: '{{ target }}'
  gather_facts: no
  tasks:
    - ansible.builtin.setup:
        gather_subset: [min]
        #filter:
        #  - ansible_date_time
        #  - ansible_uptime_seconds
        #  - ansible_loadavg
        #  - ansible_memory_mb
        #  - ansible_mounts
        #  - ansible_default_ipv4
