---

- hosts: '{{ target }}'

  gather_facts: no

  tasks:

    - name: Print Hello world to console
      ansible.builtin.debug:
        msg: "Hello world from playbook"


    - name: Include hello-world role
      include_role:
        name: hello-world
        tasks_from: main
