bind 0.0.0.0
protected-mode yes
port 6379

daemonize no
supervised no

dir /redis

save 900 1
save 300 10
save 60 10000

appendonly yes

# Redis 6+ supports ACLs. If you only need one app user, create one and disable default.
#aclfile /etc/redis/users.acl