---

- hosts: '{{ target }}'

  tasks:

    - name: Setup Docker
      import_role:
        name: docker
        tasks_from: main
      tags: [docker]

    - name: Ensure apache and nginx are not installed
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - apache2
        - nginx
      tags: [remove, apache, nginx]

#    - name: Setup Nginx
#      import_role:
#        name: nginx
#        tasks_from: main
#      tags: [nginx]
#
#
#    - name: Setup Ingress Domains
#      import_role:
#        name: nginx
#        tasks_from: domains
#      tags: [domains, ingress]
