---
- name: Check free disk space on specified Ubuntu server
  hosts: '{{ target }}'
  gather_facts: yes
  tasks:
    - name: Gather disk space information
      command: df -h /
      register: disk_space

    - name: Display disk space
      debug:
        msg: "{{ disk_space.stdout }}"

