
- name: Install fail2ban package
  apt:
    name: fail2ban
    state: present

- name: Install python3-systemd package (reads logs via journalctl)
  apt:
    name: python3-systemd
    state: present
  when: ansible_distribution == "Debian"

- name: Install iptables package
  apt:
    name: iptables
    state: present


- name: Create fail2ban.local config
  copy:
    remote_src: yes
    src: /etc/fail2ban/fail2ban.conf
    dest: /etc/fail2ban/fail2ban.local
    backup: yes
    force: no
    owner: root
    group: root
    mode: 0644


- name: Remove debian-defaults jail config
  file:
    path: /etc/fail2ban/jail.d/debian-defaults.local
    state: absent
  when: ansible_distribution == "Debian"


- name: Add sshd jail
  template:
    src: sshd-jail.j2
    dest: /etc/fail2ban/jail.d/sshd.local
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban