---

- name: Add wireguard filter
  template:
    src: wireguard-filter.j2
    dest: /etc/fail2ban/filter.d/wireguard.conf
    owner: root
    group: root
    mode: 0644


- name: Add wireguard jail
  template:
    src: wireguard-jail.j2
    dest: /etc/fail2ban/jail.d/wireguard.local
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban