---



#    - name: Install security software packages
#      apt:
#        name: "{{ item }}"
#        state: latest
#        update_cache: yes
#      with_items:
#        - fail2ban
#        - ufw
#        - iptables
#        - iptables-persistent
#        - clamav
#        - rkhunter
#        - lynis
#        - chkrootkit


- name: Disable IPv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present
    reload: yes
  tags: [ipv6]


- name: Setup fail2ban
  import_role:
    name: fail2ban
    tasks_from: main
  tags: [fail2ban]