INTEGRATIONS = [
    {"name": "docker", "description": "Docker integration", "category": "container-orchestration"},
    {"name": "kubernetes", "description": "Kubernetes integration", "category": "container-orchestration"},
    {"name": "aws", "description": "AWS integration", "category": "cloud-provider"},
    {"name": "azure", "description": "Azure integration", "category": "cloud-provider"},
    {"name": "gcp", "description": "GCP integration", "category": "cloud-provider"},
    {"name": "ansible", "description": "Ansible integration", "category": "automation"},
    {"name": "github", "description": "GitHub integration", "category": "vcs"},
    {"name": "gitlab", "description": "GitLab integration", "category": "vcs"},
    {"name": "bitbucket", "description": "Bitbucket integration", "category": "vcs"},
    {"name": "svn", "description": "SVN integration", "category": "vcs"},
    {"name": "jenkins", "description": "Jenkins integration", "category": "ci-cd"},
    {"name": "gitlab-ci", "description": "GitLab CI integration", "category": "ci-cd"},
    {"name": "circleci", "description": "CircleCI integration", "category": "ci-cd"},
    {"name": "travisci", "description": "Travis CI integration", "category": "ci-cd"},
    {"name": "prometheus", "description": "Prometheus integration", "category": "monitoring"},
    {"name": "grafana", "description": "Grafana integration", "category": "monitoring"},
    {"name": "elasticsearch", "description": "Elasticsearch integration", "category": "logging"},
    {"name": "logstash", "description": "Logstash integration", "category": "logging"},
    {"name": "kibana", "description": "Kibana integration", "category": "logging"},
    {"name": "dockerhub", "description": "Docker Hub integration", "category": "container-registry"},
    {"name": "ghcr", "description": "GitHub Container Registry integration", "category": "container-registry"},
    {"name": "aws-ecr", "description": "AWS ECR integration", "category": "container-registry"},
    {"name": "azure-acr", "description": "Azure ACR integration", "category": "container-registry"},
    {"name": "gcp-gcr", "description": "GCP GCR integration", "category": "container-registry"},
    {"name": "quay", "description": "Quay integration", "category": "container-registry"},
]
