---


- name: Install software packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - wireguard
    - iptables


- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes


- name: Debug all wg_server variables
  debug:
    var: item
  with_items:
    - wg_server_name
    - wg_server_primary_iface
    #- wg_server_private_key
    - wg_server_public_key
    - wg_server_listen_port
    - wg_server_address

- name: Debug all wg_server_peers
  debug:
      var: item
  with_items: "{{ wg_server_peers }}"
  when: wg_server_peers is defined and wg_server_peers | length > 0


- name: Check if wg_server variables are defined and not empty
  assert:
    that:
      - wg_server_name is defined and wg_server_name != ""
      - wg_server_primary_iface is defined and wg_server_primary_iface != ""
      - wg_server_private_key is defined and wg_server_private_key != ""
      - wg_server_public_key is defined and wg_server_public_key != ""
      - wg_server_listen_port is defined and wg_server_listen_port != ""
      - wg_server_address is defined and wg_server_address != ""
    fail_msg: "One or more required variables are not defined: wg_server_name, \
     wg_server_primary_iface, wg_server_private_key, wg_server_listen_port, wg_server_address"


- name: Create wireguard config
  template:
    src: wg.conf.j2
    dest: "/etc/wireguard/{{ wg_server_name }}.conf"
    owner: root
    group: root
    mode: 0600

#    - name: Stop wireguard
#      command: "wg-quick down {{ wg_server_name }}"
#      register: wg_stop
#      ignore_errors: yes
#
#    - name: Start wireguard
#      command: "wg-quick up {{ wg_server_name }}"
#      register: wg_start
#      ignore_errors: yes

- name: Enable wg-quick service
  command: "systemctl enable wg-quick@{{ wg_server_name }}"
  register: wg_service_enable
  ignore_errors: yes

- name: Start wg-quick service
  command: "systemctl stop wg-quick@{{ wg_server_name }}"
  register: wg_service_stop
  ignore_errors: yes

- name: Start wg-quick service
  command: "systemctl start wg-quick@{{ wg_server_name }}"

- name: Check if wireguard is running
  command: wg
  register: wg_status
  ignore_errors: no

- name: Display wireguard status
  debug:
    msg: "{{ wg_status.stdout }}"
  when: wg_status is defined and wg_status.rc == 0
