---


## Security
- name: Add security configuration
  template:
    src: security.conf.jinja2
    dest: /etc/nginx/conf.d/security.conf
    force: yes
    owner: root
    group: root
    mode: 0644
  notify: restart nginx