---


- name: Remove any old Certbot package
  apt:
    name: certbot
    state: absent

- name: Update apt package list
  apt:
    update_cache: yes

- name: Install snapd package
  apt:
    name: snapd
    state: present

- name: Ensure snapd.socket is enabled and started
  systemd:
    name: snapd.socket
    state: started
    enabled: yes

- name: Install core snap package
  command: snap install core
  register: core_install
  changed_when: "'installed' in core_install.stdout or core_install.rc == 0"

- name: Refresh core snap package
  command: snap refresh core

- name: Install Certbot using Snap with classic confinement
  command: snap install --classic certbot
  register: certbot_install
  changed_when: "'installed' in certbot_install.stdout or certbot_install.rc == 0"

- name: Create symbolic link for Certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
    force: yes

- name: Verify Certbot installation
  command: certbot --version
  register: certbot_version

- debug:
    msg: "Installed Certbot version: {{ certbot_version.stdout }}"
