
docker_users: []  # List of users to add to the 'docker' group

docker_plugin_compose: True  # Whether to install the docker compose plugin
docker_plugin_model: False  # Whether to install the docker model-runner plugin