
wg_server_name: "wg0"
wg_server_private_key: # should be in a vault
wg_server_public_key: # should be in a vault
wg_server_address: # "10.8.0.1/24"
wg_server_listen_port: 51820
wg_server_primary_iface: "{{ ansible_default_ipv4.interface }}"
wg_server_endpoint: "{{ ansible_default_ipv4.address }}:{{ wg_server_listen_port }}" # "example.org:51820"

wg_server_peers: []
#  - name: "example_peer"
#    public_key: "1xDBa2jW2FnzFeFhLvw+Mbh+4RlTPKQ7ejXwBDrT8mU="
#    allowed_ips: "10.8.0.2/32"
#    #endpoint: "example.org:51820"
#    #persistent_keepalive: 25
#    #pre_shared_key: "example_pre_shared_key"
