import typer

from deployr.app import app as deployr_app

app = typer.Typer()
app.add_typer(deployr_app, name="deploy", help="Deployment related commands")

if __name__ == "__main__":
    app()

# deploy_strategy = "blue-green"
# deploy_strategy = "canary"
# deploy_strategy = "rolling"
# deploy_strategy = "recreate"
# deploy_strategy = "shadow"
# deploy_strategy = "a-b"
# deploy_strategy = "highlander"
# deploy_strategy = "immutable"
#
# deploy_pipeline = "rsync"
# deploy_pipeline = "docker"
# deploy_pipeline = "kubernetes"
# deploy_pipeline = "terraform"
# deploy_pipeline = "ansible"
# deploy_pipeline = "helm"
# deploy_pipeline = "pulumi"
# deploy_pipeline = "cloudformation"
# deploy_pipeline = "serverless"
# deploy_pipeline = "jenkins"
# deploy_pipeline = "github-actions"
# deploy_pipeline = "gitlab-ci"
# deploy_pipeline = "circleci"
# deploy_pipeline = "travis-ci"
# deploy_pipeline = "bitbucket-pipelines"
#
# deploy_preset = "react-spa"
# deploy_preset = "vue-spa"
# deploy_preset = "angular-spa"
# deploy_preset = "nextjs"
# deploy_preset = "nuxtjs"
# deploy_preset = "sveltekit"
# deploy_preset = "flask"
# deploy_preset = "django"
# deploy_preset = "express"
# deploy_preset = "spring-boot"
# deploy_preset = "laravel"
# deploy_preset = "ruby-on-rails"
# deploy_preset = "wordpress"
# deploy_preset = "static-site"
# deploy_preset = "microservice"
# deploy_preset = "serverless-function"
# deploy_preset = "containerized-app"
# deploy_preset = "database"
# deploy_preset = "cdn"
# deploy_preset = "api-gateway"
# deploy_preset = "message-queue"
# deploy_preset = "cache"
# deploy_preset = "load-balancer"
# deploy_preset = "monitoring"
# deploy_preset = "logging"
# deploy_preset = "ci-cd-pipeline"
# deploy_preset = "infrastructure-as-code"
# deploy_preset = "configuration-management"
# deploy_preset = "orchestration"
# deploy_preset = "version-control"
# deploy_preset = "artifact-repository"
# deploy_preset = "secret-management"
# deploy_preset = "service-mesh"
# deploy_preset = "edge-computing"
# deploy_preset = "iot-deployment"
# deploy_preset = "big-data-pipeline"
# deploy_preset = "machine-learning-model"
# deploy_preset = "blockchain-node"
# deploy_preset = "gaming-server"
# deploy_preset = "video-streaming"
# deploy_preset = "chat-application"
# deploy_preset = "e-commerce-platform"
# deploy_preset = "crm-system"
# deploy_preset = "erp-system"
# deploy_preset = "cms"
#
# deploy_src = "file://dist/"
# deploy_src = "github://myuser/myrepo/"
# deploy_src = "gitlab://myuser/myrepo/"
# deploy_src = "bitbucket://myuser/myrepo/"
# deploy_src = "gitea://myuser/myrepo/"
# deploy_src = "azure-repos://myuser/myrepo/"
# deploy_src = "git://myserver.com/myrepo.git"
# deploy_src = "svn://myserver.com/myrepo"
#
#
# deploy_target = "s3://mybucket/app/"
# deploy_target = "ec2://mybucket/app/"
# deploy_target = "vercel://myproject/"
# deploy_target = "netlify://myproject/"
# deploy_target = "github-pages://myuser/myrepo/"
# deploy_target = "ftp://myserver.com/deploy/"
# deploy_target = "scp://myserver.com/deploy/"
# deploy_target = "rsync://myserver.com/deploy/"
# deploy_target = "ssh://myserver.com/deploy/"
# deploy_target = "azure://mycontainer/app/"
# deploy_target = "gcs://mybucket/app/"
# deploy_target = "heroku://myapp/"
# deploy_target = "digitalocean://myapp/"
# deploy_target = "linode://myapp/"
# deploy_target = "cloudflare://myapp/"
# deploy_target = "render://myapp/"
# deploy_target = "fly://myapp/"
# deploy_target = "netcup://myapp/"

